# Generated by Django 4.2 on 2024-06-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=30)),
                ('guardian_name', models.CharField(max_length=15)),
                ('event_type', models.CharField(max_length=20)),
                ('participants', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('day', models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=10)),
                ('month', models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=10)),
                ('strt_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('time_category', models.CharField(choices=[('FULL', 'Full Day'), ('FORE', 'Half Day (Before Noon)'), ('AFTR', 'Half Day (After Noon)')], max_length=10)),
                ('amenities', models.ManyToManyField(blank=True, to='MainApp.amenity')),
            ],
        ),
    ]
