# Generated by Django 4.2 on 2024-06-24 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenity',
            old_name='amenities',
            new_name='amenity',
        ),
    ]
