# Generated by Django 4.2 on 2024-06-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_rename_amenities_amenity_amenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='events', to='MainApp.amenity'),
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='month',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='strt_time',
            field=models.TimeField(blank=True),
        ),
    ]
